### ISSUE TITLE
sphinx autodocs fails with error in tuple dataclass?

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#409]
## Description

Trying to generate docs automatically using sphinx

## Environment

Most recent conda_wps env build and raven installed.

## Steps to Reproduce

navigate to docs and 'make html'. I had do pip install:
-- nbsphinx
-- sphinx_rtd_theme

Also had to fix a few problems in installation.rst including title level inconsistencies and a few indentations.

But now the error I am getting is more serious:

```
(raven-wps) ets@etsml:~/src/ravenDocs/raven/docs$ make html
Running Sphinx v4.2.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 36 source files that are out of date
updating environment: [new config] 36 added, 0 changed, 0 removed
reading sources... [100%] processes                                                                                                                                               

Warning, treated as error:
autodoc: failed to import process 'processes.RavenProcess' from module 'raven'; the following exception was raised:
Traceback (most recent call last):
  File "/home/ets/anaconda3/envs/raven-wps/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/ets/anaconda3/envs/raven-wps/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ets/src/ravenDocs/raven/raven/processes/__init__.py", line 22, in <module>
    from .wps_ostrich_gr4j_cemaneige import OstrichGR4JCemaNeigeProcess
  File "/home/ets/src/ravenDocs/raven/raven/processes/wps_ostrich_gr4j_cemaneige.py", line 52, in <module>
    default=", ".join(map(str, astuple(Uparams_defaults))),
  File "/home/ets/anaconda3/envs/raven-wps/lib/python3.7/dataclasses.py", line 1128, in astuple
    raise TypeError("astuple() should be called on dataclass instances")
TypeError: astuple() should be called on dataclass instances

make: *** [Makefile:23: html] Error 2

```

I have no idea how to fix this or if my process is OK. Any help appreciated!

**Comment by Zeitsperre** [comment]
@richardarsenault Can you try navigating to the top-level and running `make develop` (to install the docs-building dependencies) and then running `make docs` ?

**Comment by Zeitsperre** [comment]
That's really odd. The location of the environments should be fine, unless you're working on RavenPy while trying to build the RavenWPS docs. There might be some inconsistency there?

I've been having no issue building the docs on my side. Would a video call on Slack make sense at this point?

**Comment by richardarsenault** [comment]
I tried again today and all works, for both RavenPy and RavenWPS, so no idea what changed but this is irrelevant now. Thanks anyways!

**Comment by Zeitsperre** [comment]
@richardarsenault I'll take that as a win. :laughing:
