### ISSUE TITLE
Make start fails on new install

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#74]
## Description
After make install (successful), make start gives the following error:

Starting application ...
Traceback (most recent call last):
  File "/home/ets/anaconda3/envs/raven/bin/raven", line 11, in <module>
    load_entry_point('raven', 'console_scripts', 'raven')()
  File "/home/ets/anaconda3/envs/raven/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ets/anaconda3/envs/raven/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/ets/anaconda3/envs/raven/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/ets/anaconda3/envs/raven/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'raven.cli'; 'raven' is not a package
Makefile:105: recipe for target 'start' failed
make: [start] Error 1 (ignored)

## Environment

* Raven version used, if any:
* Python version, if any: Python 3.6
* Operating System: Linux Mint 18.X

## Steps to Reproduce
git init (in new folder)
git clone [...]
make install
make start

```
Paste the command(s) you ran and the output.
```
See above

## Additional Information

Links to other issues or sources.

**Comment by richardarsenault** [comment]
Anaconda3 -> miniconda + fresh install fixed this error
